"use client"

import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import SideNavbar from '@/components/Sidebar';

import "./globals.css";
import { useWebSocket } from "@/hooks/useWebSocket";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { messages } = useWebSocket("ws://localhost:8080");

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <SideNavbar />
          <div className="flex-grow">
            {messages.length > 0 && (
              <div className="fixed bottom-4 right-4 bg-white p-4 border rounded shadow-lg">
                <h2 className="font-bold">New Request</h2>
                <p>{messages[0]}</p>
              </div>
            )}
            {children}
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
